### ISSUE TITLE
Support woff fonts

### ISSUE THREAD

**Issue by pgundlach** [bmaupin/go-epub#12]
When I try to add a `woff` font, I get the following error:

```
panic: Unmatched file extension, media type not set for file: roboto-mono-v5-latin-300.woff
````

Is it possible to add support these fonts?

See https://www.w3.org/publishing/epub3/epub-spec.html#sec-cmt-supported

**Comment by bmaupin** [comment]
I just added support for woff and woff2 fonts and tagged a new release ([v0.5.2](https://github.com/bmaupin/go-epub/releases/tag/v0.5.2)).

Thanks!
