### ISSUE TITLE
No thumbnail on MacOS

### ISSUE THREAD

**Issue by gonejack** [bmaupin/go-epub#18]
![image](https://user-images.githubusercontent.com/2720676/110911773-1355a600-834e-11eb-9f7b-f1db123ca601.png)

No thumbnail for the original one.

By dragging `origin.epub` into Apple Books then drag it out, the `export.epub`, it got thumbnail. 

[epubs.zip](https://github.com/bmaupin/go-epub/files/6128512/epubs.zip)

**Comment by gonejack** [comment]
I notice that all .epub files made by https://github.com/gonejack/rss-epub with https://github.com/cyrilis/epub-gen has no issue with thumbnail on MacOS.


[博客_2021-04-02_10-41-41.epub.zip](https://github.com/bmaupin/go-epub/files/6247538/_2021-04-02_10-41-41.epub.zip)

**Comment by bmaupin** [comment]
I saw you attached a zip file with the epubs before and after importing them into Apple Books. Could you figure out what the minimal needed changes are in order to fix this? Thanks!
