### ISSUE TITLE
Invalid release tags

### ISSUE THREAD

**Issue by roger-russel** [bmaupin/go-epub#42]
Golang tags must be vMAJOR.MINOR.PATCH always.

The tag v0.7 is invalid, and it can't be importated into another project, it must have the patch number on it like this v0.7.0.

For further information please take a look into https://blog.golang.org/publishing-go-modules

**Comment by bmaupin** [comment]
Good catch, thanks! This should be fixed now. 

Some notes for my future self in case I accidentally do this again:

There doesn't seem to be a way to rename a tag through the GitHub UI. Renaming a release will create a new tag but seems to lose the commit ID. The best way to fix this seems to be:

1. In the command line, create a new tag pointing to the old one

   ```
   git tag v0.7.0 v0.7
   ```

1. Push the new tag

   ```
   git push origin v0.7.0
   ```

   (Maybe `git push` or `git push --tags` would work too?)

1. In the GitHub UI, edit the release and point to the new tag
1. In the command line, delete the old tag locally and remotely

   ```
   git push origin :v0.7
   git tag -d 0.7
   ```
   
   (Or maybe `git tag -d 0.7` and then `git push --tags` would work?)
