### ISSUE TITLE
First filename section0002.xhtml

### ISSUE THREAD

**Issue by gonejack** [bmaupin/go-epub#43]
Hi @bmaupin

I got a issue report https://github.com/gonejack/html-to-epub/issues/1 about section file naming.

Would you like to resolve it or I would like to make a PR later.

**Comment by bmaupin** [comment]
Up to you. You're welcome to make a PR as long as it meets the requirements
in https://github.com/bmaupin/go-epub/blob/main/CONTRIBUTING.md

Thanks!

**Comment by bmaupin** [comment]
Closed by #44
