### ISSUE TITLE
Update documentation for data URLs

### ISSUE THREAD

**Issue by bmaupin** [bmaupin/go-epub#48]
The documentation needs to be updated for #45 before we can make a new release, e.g. this only mentions URLs and local files: https://pkg.go.dev/github.com/bmaupin/go-epub?utm_source=godoc#Epub.AddCSS

**Comment by owulveryck** [comment]
I can take this action if you want;

BTW, the `validateFileSource` function prevents the usage of the dataurl scheme.
I wonder whether this validation is required ?

**Comment by bmaupin** [comment]
> I can take this action if you want;

Sure, that'd be great, thanks.

> BTW, the `validateFileSource` function prevents the usage of the dataurl scheme.

That's odd. Any idea why the tests aren't catching this?

> I wonder whether this validation is required ?

It's been a long time since I wrote that, but IIRC the goal was to throw an error as soon as possible. Otherwise, if for example, somebody used `AddImage` with an invalid URL/file, it wouldn't throw the error until the file was actually written, which doesn't occur until `Write` is called.
