### ISSUE TITLE
Two mimetype file created when running on Windows machine

### ISSUE THREAD

**Issue by nitxy** [bmaupin/go-epub#59]
On the `writeEpub` function of `write.go`, it seems that calling `filepath.Join(rootEpubDir, mimetypeFilename)` on a Windows machine would generate a path joined by a backslash `\` instead of usual forward slash `/`.

Calling `fs.WalkDir(filesystem, rootEpubDir, addFileToZip)` later would result in comparing forward slash path of mimetype with the backslash version by `filepath.Join(rootEpubDir, mimetypeFilename)` which in the end resulting with another mimetype with deflate method.

Changing `path == filepath.Join(rootEpubDir, mimetypeFilename)` to `filepath.Base(path) == mimetypeFilename` would be a quick fix but there might be a better way to do this.

**Comment by bmaupin** [comment]
I don't have access to a Windows machine to test this on, but maybe I could create a breaking test and run it in GitHub Actions so I can make sure the fix is working.

If you get a chance, could you attach an EPUB with the extra mimetype file to this issue? Thanks!

**Comment by bmaupin** [comment]
Because I don't have a Windows machine, I'm not really able to test this, so I'll mark it as *Help wanted* for now.

I did do some quick research and found this:

> For creating and manipulating OS-specific paths directly use [os.PathSeparator](http://golang.org/pkg/os) and the [path/filepath](http://golang.org/pkg/path/filepath/) package.
> 
> An alternative method is to always use '/' and the [path](http://golang.org/pkg/path/) package throughout your program. The path package uses '/' as path separator irrespective of the OS. Before opening or creating a file, convert the /-separated path into an OS-specific path string by calling [filepath.FromSlash(path string)](http://golang.org/pkg/path/filepath/#FromSlash). Paths returned by the OS can be converted to /-separated paths by calling [filepath.ToSlash(path string)](http://golang.org/pkg/path/filepath/#ToSlash).

https://stackoverflow.com/a/9373342/399105

@nitxy I see you're new to GitHub. Are you familiar with pull requests? I'm asking because if you don't know them and are interested in learning, this would be a perfect issue to learn them since it's a small one:

https://docs.github.com/en/pull-requests

**Comment by bmaupin** [comment]
Fixed by #61
