### ISSUE TITLE
Incorrect subsection title in TOC

### ISSUE THREAD

**Issue by nitxy** [bmaupin/go-epub#60]
On line 444 of `write.go`,
`e.toc.addSubSection(relativePath, index, section.xhtml.Title(), relativeSubPath)`
should be
`e.toc.addSubSection(relativePath, index, child.xhtml.Title(), relativeSubPath)`
or else the title of all child sections displayed on TOC would be the same with their parent

https://github.com/bmaupin/go-epub/blob/main/write.go#L444

**Comment by bmaupin** [comment]
Since you've already figured out the fix, (similarly to #59) if you're interested in submitting a pull request, let me know. Otherwise I can take a look.

Thanks!

**Comment by bmaupin** [comment]
Fixed by #61
