### ISSUE TITLE
Transferring this project

### ISSUE THREAD

**Issue by bmaupin** [bmaupin/go-epub#68]
Hi everyone,

As I mentioned in #28, I don't actually use this project any more. I've tried to maintain it over the last couple of years but at this point it doesn't make much sense for me to keep working on it with the limited time that I have.

I'd like to handle the transition as smoothly as possible so that it doesn't break for anyone. I've created a new [go-epub organisation](https://github.com/go-epub) as my first thought is to transfer this project there. My understanding is that GitHub will automatically create a Git redirect so that it won't break for anyone using this library with the old Git URL.

It's due for a new major release anyway due to the new Go version requirements as part of #66, so I think this would be a good time to make the change.

@owulveryck You're the only other maintainer at the moment so I don't want to just dump this on you without consulting you first. Some options I see:

- Transfer the project to the new go-epub organisation as-is, leaving its future in your hands. I can stick around as a maintainer long enough to help transfer the project, update the README, etc.
- Transfer the project and add some more maintainers. @fmartingr has expressed some interest.
- Archive the project and allow it to evolve naturally. I guess whoever creates a fork and maintains it will become the de-facto maintainer, and if a particular fork stands out I can update the readme and point to it

What do you think? It's been 2 years since I created #28 so there's no urgency to make a decision right away, but I wanted to start the conversation.

**Comment by fmartingr** [comment]
As said before we are going to use it in [go-shiori/shiori](https://github.com/go-shiori/shiori) so we'll be happy to help with the library.

I don't mind doing regular reviews and maintenance though @monirzadeh is the one that have contributed the code changes so he may have something to say as well.

To propose other alternatives:
- You could leave the project where it is, giving granular access no new maintainers.
- We could adopt the project under the [go-shiori](https://github.com/go-shiori) organization, of course giving access to current maintainers.

I'm assuming that if we reach your point #3, we'll just fork it under our umbrella anyway, but I'd rather try some of the other options first.

**Comment by owulveryck** [comment]
Hello;

Sorry for the delay. To be honest I don’t have time to maintain this project either (even my other project which is using this library is stalled).

I guess that transferring it to the new organization is the best idea.

I don’t know how it works under the hood; would it break the current dependencies (I mean, the projects that are using this library).
If this is the case, it would be better to archive this one and fork it in the new organization.

**Comment by bmaupin** [comment]
Thanks for everyone's input.

I think what I'd like to do is go ahead and archive this project. That will leave it as-is, frozen in time as a stable v1 release.

I'll also go ahead and delete the go-epub organisation I created in case anyone wants to re-create it later.

@fmartingr I like your idea of forking it in your go-shiori organisation. After you fork it (and before I archive it), would you like me to add a note to the readme of this project pointing to your fork?

Thanks!

**Comment by fmartingr** [comment]
> @fmartingr I like your idea of forking it in your go-shiori organisation. After you fork it (and before I archive it), would you like me to add a note to the readme of this project pointing to your fork?

Sure! I've gone ahead and forked it already. I will need some time to setup workflows, versioning, namespaces and so on, but that way you can finish your work in this repository :)

Thanks for the help and quick responses along the way, I hope we take good care of the library moving forward :)
