### ISSUE TITLE
request: Use HTTP Content-Type header value

### ISSUE THREAD

**Issue by AmandaCameron** [bmaupin/go-epub#8]
Not sure if that's acceptible in the epub spec, but I'm working on a program to convert some various web sources into .epubs for downlod, and one of the sources I'm using has a `.bmp` on it which is causing the system to fail.

Another thought might be, when a url is passed to `AddImage` it could use the returned `Content-Type` instead of trying to divine it from the file name, at least for images.

**Comment by bmaupin** [comment]
It looks like BMP isn't one of the core media types included in the EPUB spec:

https://idpf.github.io/epub-cmt/v3/#sec-cmt-supported

While that doesn't necessarily stop you from creating an EPUB with BMP files in it, I'm not sure if it'd be valid and it may cause problems when it comes time to read it, so I'm not sure if something like this should be added to the library.

Would it be possible to convert them instead? Something like this ought to work:

    convertBmpToPing("/path/to/test.bmp", "/path/to/test.png")

    func convertBmpToPing(inputBmpPath string, outputPngPath string) error {
        inputBmpFile, err := os.Open(inputBmpPath)
        if err != nil {
            return err
        }

        decodedImage, err := bmp.Decode(inputBmpFile)
        if err != nil {
            return err
        }

        outputPngFile, err := os.Create(outputPngPath)
        if err != nil {
            return err
        }

        err = png.Encode(outputPngFile, decodedImage)
        if err != nil {
            return err
        }

        return nil
    }

What do you think?

**Comment by AmandaCameron** [comment]
That'd certinely be a possibility, and since bmp isn't mentioned in the epub spec, I agree it'd probably be best not to include it in the conversaion table.

However, for the other part of using the content-type header in the result, I think that should still be considered.

**Comment by bmaupin** [comment]
> However, for the other part of using the content-type header in the result, I think that should still be considered.

Yeah, I think that could definitely add value. I don't have time to implement this at the moment, but pull requests are welcome :)
